language: java
jdk:
        - openjdk8

branches:
        only:
                - master

cache:
        directories:
                - '$HOME/.m2/repository'
                - '$HOME/.mvnw'

before_install:
        - chmod +x mvnw

script: "./mvnw clean package"

notifications:
        email:
                recipients:
                        - bjtlr@naver.com

